from services.chains import sql_generation_chain
from db.user_db.user_db_schema import schema_text
import json
import uuid
import re

FORBIDDEN_KEYWORDS = [
    "DROP",
    "DELETE",
    "UPDATE",
    "INSERT",
    "ALTER",
    "TRUNCATE",
    "CREATE",
    "REPLACE"
]

def validate_sql_query(query: str) -> None:
    """
    Validates generated SQL query for safety.
    Raises ValueError if query is unsafe.
    """

    if not query:
        raise ValueError("Empty SQL query generated")

    normalized = query.strip().upper()

    # 1️⃣ Must start with SELECT
    if not normalized.startswith("SELECT"):
        raise ValueError("Only SELECT queries are allowed")

    # 2️⃣ Block forbidden keywords
    for keyword in FORBIDDEN_KEYWORDS:
        if re.search(rf"\b{keyword}\b", normalized):
            raise ValueError(f"Unsafe SQL operation detected: {keyword}")

    # 3️⃣ Block multiple statements
    if ";" in normalized[:-1]:
        raise ValueError("Multiple SQL statements are not allowed")

    # 4️⃣ Block SQL comments
    if "--" in normalized or "/*" in normalized or "*/" in normalized:
        raise ValueError("SQL comments are not allowed")
    

def generate_sql(question: str):

    response = sql_generation_chain.invoke({
        "question": question,
        "schema": schema_text
    })

    return response



def format_generate_sql_response(
    llm_response: str,
    user_id: str,
    natural_language_query:str
) -> dict:
    res_id = f"que_{uuid.uuid4().hex[:8]}"

    # 1️⃣ Parse JSON
    try:
        parsed = json.loads(llm_response)
    except json.JSONDecodeError:
        return {
            "status": 0,
            "user_id": user_id,
            "data": {
                "error": "Invalid response generated by LLM",
                "suggestion": "Please try rephrasing your question.",
                "natural_language_query":natural_language_query,
                "res_id": res_id
            }
        }

    # 2️⃣ SUCCESS CASE (query generated)
    if "query" in parsed:
        try:
            validate_sql_query(parsed.get("query"))
        except ValueError as e:
            return {
                "status": 0,
                "user_id": user_id,
                "data": {
                    "error": "Unsafe SQL query generated",
                    "suggestion": str(e),
                    "natural_language_query":natural_language_query,
                    "res_id": res_id
                }
            }

        return {
            "status": 1,
            "user_id": user_id,
            "data": {
                "query": parsed.get("query"),
                "details": parsed.get("details") or parsed.get("explanation"),
                "language": parsed.get("language"),
                "natural_language_query":natural_language_query,
                "res_id": res_id
            }
        }

    # 3️⃣ ERROR CASE (LLM says query cannot be generated)
    return {
        "status": 0,
        "user_id": user_id,
        "data": {
            "error": parsed.get("error"),
            "suggestion": parsed.get("suggestion"),
            "natural_language_query":natural_language_query,
            "res_id": res_id
        }
    }